# ==========================================
# APPLICATION INFO
# ==========================================
spring.application.name=erpadmin
server.port=8080

# ==========================================
# DATABASE - PostgreSQL
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# ==========================================
# JPA / HIBERNATE
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.open-in-view=false

# ==========================================
# THYMELEAF
# ==========================================
spring.thymeleaf.cache=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

# ==========================================
# LOGGING - PRODUCCION
# ==========================================
#logging.level.root=WARN
#logging.level.lat.jbluesoft=INFO
#logging.level.org.springframework.web=WARN
#logging.level.org.springframework.security=WARN
#logging.level.org.hibernate.SQL=WARN
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%level] - %msg%n
#logging.file.name=/var/log/erpadmin/erpadmin.log
#logging.logback.rollingpolicy.max-file-size=10MB
#logging.logback.rollingpolicy.max-history=30